services:
  app:
    build:
      context: .
      target: prod
    command: node src/index.js
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 5001:5001
    labels:
      - 'caddy_0.basicauth.0_admin=$$2a$$14$$jbGmk7lnXwYaCP9qfvRbkOpJLHCzwu4h3QDYj568HCxYCWaM/Ziyu'
      - 'service.name=docker-compose-example'
  redis:
    image: redis:7.2.4
