services:
  app:
    build:
      context: .
      target: prod
    command: node src/index.js
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 5001:5001
  redis:
    image: redis:7.2.4